# Generated by Django 3.0.8 on 2020-07-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='filesname',
            new_name='filename',
        ),
    ]
