# Generated by Django 2.2 on 2020-06-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
