# Generated by Django 3.0.8 on 2020-07-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200703_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
